### ISSUE TITLE
Pausable/Resumable Downloads

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-backend#14]
Pausable/Resumable chunk-based file transfer.

Perhaps even implement a system similar to torrents, where a remote client that has already downloaded a file can also share it with other remote clients.

**Comment by KairuByte** [comment]
> Perhaps even implement a system similar to torrents, where a remote client that has already downloaded a file can also share it with other remote clients. (Legality?)

Assuming you are talking about this only happening between clients that are attached to the specific back end, the only way this would run into legal hot water is if the file being transferred is itself illegal. There is nothing inherently illegal about P2P transfers.

That said, it may be a good idea to have something like that be optional, since many times the end user will likely have abysmal upload speeds.

**Comment by Alfagun74** [comment]
Server Downloads now support the [HTTP "Ranges" Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range).

**Comment by Yelo420** [comment]
Also implemented in the Client
