### ISSUE TITLE
It would be awesome if gamevault could support MariaDB

### ISSUE THREAD

**Issue by MichelM279** [Phalcode/gamevault-backend#211]
**Is your feature request related to a problem? Please describe.**
I would love if gamevault could support MariaDB. 
It's not a problem per se, but I have a personal preference for MariaDB, as I have one setup with auto backups, access mgmt, etc.. And if I setup a postgres container, I'd have to jump through all those hoops again to get the container to as high quality as my MariaDB.
I'm hoping to find similar-minded people who also would like MariaDB. If I am alone in this request, I'll kindly accept that gamevault stays on one DB.

**Describe the solution you'd like**
Be able to use MariaDB, knowing that it will be included in tests, etc. to work today and in the future.

**Describe alternatives you've considered**
Setting up postgres :)

**Comment by Alfagun74** [comment]
I see where you are coming from, but although our ORM Typeorm supports MariaDB easily, maintaining a third set of database migrations sounds like a huuuge pain in the ass for me. I would only do this if it is **heavily** requested by the community otherwise, i need to write/generate my migratons and test them thrice before going on when developing :/

**Comment by MichelM279** [comment]
I fully respect that

**Comment by Alfagun74** [comment]
Thank you for understanding. Perhaps we will revisit this in the future. 

However, with your particular use case, it is generally a better idea to have separate databases for each application that you self-host. This approach helps prevent one application from inadvertently affecting or damaging another when restoring backups or performing similar critical operations.
